dist: focal
os: linux
sudo: false
language: python

matrix:
  include:
    - env: TOXENV=django111-py36
      python: 3.6
    - env: TOXENV=django20-py36
      python: 3.6
    - env: TOXENV=django22-py310
      python: "3.10.0"
    - env: TOXENV=django32-py310
      python: "3.10.0"
    - env: TOXENV=django40-py310
      python: "3.10.0"

install:
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls
